const http=require('http');
const {spawn}=require('child_process');
const fs=require('fs');
const os=require('os');
const path=require('path');
const chrome='C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';
const port=9300+Math.floor(Math.random()*1000);
const targetUrl=process.argv[2]||'http://127.0.0.1:5173/';
const wait=ms=>new Promise(r=>setTimeout(r,ms));
function requestJson(path,method='GET'){return new Promise((resolve,reject)=>{const req=http.request({host:'127.0.0.1',port,path,method},res=>{let data='';res.on('data',c=>data+=c);res.on('end',()=>{try{resolve(JSON.parse(data));}catch(e){reject(e);}});});req.on('error',reject);req.end();});}
async function main(){
 const profileDir=fs.mkdtempSync(path.join(os.tmpdir(),'apex-qa-soccer-runtime-'));
 const child=spawn(chrome,['--headless=new','--disable-gpu','--no-first-run','--disable-extensions',`--user-data-dir=${profileDir}`,`--remote-debugging-port=${port}`,'about:blank'],{stdio:'ignore'});
 try{
  for(let i=0;i<80;i++){try{await requestJson('/json/version');break;}catch{await wait(100);}}
  const created=await requestJson(`/json/new?${encodeURIComponent(targetUrl)}`,'PUT');
  const ws=new WebSocket(created.webSocketDebuggerUrl);let id=0;const pending=new Map(),errors=[];
  const send=(method,params={})=>new Promise((resolve,reject)=>{const callId=++id;pending.set(callId,{resolve,reject});ws.send(JSON.stringify({id:callId,method,params}));});
  ws.addEventListener('message',m=>{const data=JSON.parse(m.data);if(data.id&&pending.has(data.id)){const p=pending.get(data.id);pending.delete(data.id);data.error?p.reject(new Error(JSON.stringify(data.error))):p.resolve(data.result);}else if(data.method==='Runtime.exceptionThrown')errors.push(data.params.exceptionDetails.exception?.description||data.params.exceptionDetails.text);});
  await new Promise(r=>ws.addEventListener('open',r,{once:true}));await send('Runtime.enable');await send('Page.navigate',{url:targetUrl});
  const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value;};
  let ready=false;for(let i=0;i<120;i++){try{ready=await evaluate(`Boolean(window.APEX_SOCCER&&window.startSpecificMatch&&window.apexFighterTypes?.find(x=>x.name==='SOCCER'))`);}catch{}if(ready)break;await wait(250);}if(!ready)throw new Error('SOCCER runtime did not become ready');
  await evaluate(`(()=>{const t=window.apexFighterTypes;startSpecificMatch(t.find(x=>x.name==='SOCCER'),t.find(x=>x.name==='ICE'),{p1Hp:1000,p2Hp:1000});cancelAnimationFrame(reqId);window.__qaSoccerTick=dt=>{lastTime+=dt*1000;return window.APEX_SOCCER.preUpdate(dt);};return true;})()`);await wait(400);
  const interruption=await evaluate(`(()=>{const f=fighters.find(x=>x.name==='SOCCER'),e=fighters.find(x=>x!==f),d=f.data,b=d.soccerBall;f.x=300;f.y=500;e.x=720;e.y=500;f.data.positionLocked=false;Object.assign(d,{soccerPossessionActive:false,soccerPossessionCooldown:4,soccerCooldownKickTimer:0,soccerGoalDriveActive:false,soccerShotResolving:false,soccerPenaltyCinematicActive:false,soccerChaseDownActive:false,soccerCarryActive:false,soccerOneTouchKick:null});Object.assign(b,{state:'SOCCER_FREE_BALL',x:f.x+f.radius+b.radius,y:f.y,vx:0,vy:0,speed:0,freeFlightTime:5.2,hasLeftOwnerRadius:true,ownerContactActive:false,opponentContactActive:false});__qaSoccerTick(.001);const started=!!d.soccerOneTouchKick;Object.assign(b,{state:'SOCCER_FREE_BALL',x:800,y:800,vx:500,vy:0,speed:500,hasLeftOwnerRadius:true,ownerContactActive:false});__qaSoccerTick(1/60);return{started,cancelled:!d.soccerOneTouchKick,unlocked:!f.data.positionLocked,kickType:d.soccerCurrentKickType};})()`);
  const vfxCleanup=await evaluate(`(()=>{const s=window.APEX_SOCCER;s.vfx.length=0;for(let i=0;i<210;i++)s.vfx.push({type:'wall_spark',x:100,y:100,life:i<20?-.1:1,maxLife:1});__qaSoccerTick(1/60);return{length:s.vfx.length,expired:s.vfx.filter(x=>x.life<=0).length};})()`);
  const stress=await evaluate(`(()=>{const f=fighters.find(x=>x.name==='SOCCER'),e=fighters.find(x=>x!==f),d=f.data,b=d.soccerBall;let seed=928371,steps=0;const failures=[];const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};for(let test=0;test<80;test++){f.x=250+random()*500;f.y=250+random()*500;e.x=160+random()*680;e.y=160+random()*680;f.hp=f.maxHp=100000;e.hp=e.maxHp=100000;f.statuses={};e.statuses={};f.data.positionLocked=false;Object.assign(d,{soccerPossessionActive:false,soccerFieldOverlayActive:false,soccerPossessionCooldown:5,soccerCooldownKickTimer:0,soccerGoalDriveActive:false,soccerChaseDownActive:false,soccerCarryActive:false,soccerShotResolving:false,soccerPenaltyCinematicActive:false,soccerOneTouchKick:null,soccerCurrentKickType:null});const a=random()*Math.PI*2,s=120+random()*2010;Object.assign(b,{state:'SOCCER_FREE_BALL',x:b.radius+random()*(1000-b.radius*2),y:b.radius+random()*(1000-b.radius*2),vx:Math.cos(a)*s,vy:Math.sin(a)*s,speed:s,freeFlightTime:0,hasLeftOwnerRadius:true,lastReleaseTime:-99,ownerContactActive:false,opponentContactActive:false,sameTargetHitCooldown:{},skillShot:null,trail:[]});let overlapFrames=0;for(let frame=0;frame<120;frame++){__qaSoccerTick(1/60);steps++;const finite=[b.x,b.y,b.vx,b.vy,b.speed].every(Number.isFinite),inBounds=b.x>=b.radius-.01&&b.x<=1000-b.radius+.01&&b.y>=b.radius-.01&&b.y<=1000-b.radius+.01,overlap=Math.hypot(b.x-f.x,b.y-f.y)<f.radius+b.radius-2;overlapFrames=overlap?overlapFrames+1:0;if(!finite||!inBounds||b.trail.length>7||overlapFrames>2){failures.push({test,frame,finite,inBounds,trail:b.trail.length,overlapFrames,state:b.state,speed:b.speed});break;}}}return{steps,failures};})()`);
  const pass=interruption.started&&interruption.cancelled&&interruption.unlocked&&interruption.kickType===null&&vfxCleanup.length===180&&vfxCleanup.expired===0&&stress.steps===9600&&stress.failures.length===0&&errors.length===0;
  console.log(JSON.stringify({pass,interruption,vfxCleanup,stress,errors},null,2));if(!pass)process.exitCode=1;ws.close();
 }finally{child.kill();try{fs.rmSync(profileDir,{recursive:true,force:true});}catch{}}
}
main().catch(e=>{console.error(e.stack||String(e));process.exit(1);});
